# Убрал билды для docker, решил запускать через приложение (в тз об этом не говорится)
version: '3.8'

services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports: [ "6543:5432" ]
    environment:
      - POSTGRES_DB=stat-server
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 10

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports: [ "6542:5432" ]
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 10
