# Название приложения
spring:
  application:
    name: gateway
  # Получаем настройки из Config-server используя Eureka
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000

#Регистрация в Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  #  Указываем, как будет происходить регистрация в eureka
  instance:
    preferIpAddress: true
    instance-id: "${spring.application.name}:${random.value}"
    #   периодичность подачи сигнала о работоспособности в eureka
    leaseRenewalIntervalInSeconds: 10
    #   время ожидания сигнала eureka, если сигнал о работоспособности не постает, прежде чем Eureka его отключит
    leaseExpirationDurationInSeconds: 30
      # не сразу регистрироваться в eureka
    initialStatusReplicationDelayInSeconds: 2