# Название приложения
spring:
  application:
    name: gateway
  # Получаем настройки из Config-server используя Eureka
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        # повторное подключение
        max-attempts: 15
        initial-interval: 2000
        max-interval: 10000
        multiplier: 1.5

#Регистрация в Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  #  Указываем, как будет происходить регистрация в eureka
  instance:
    preferIpAddress: true
    instance-id: "${spring.application.name}:${random.value}"
    #   периодичность подачи сигнала о работоспособности в eureka
    leaseRenewalIntervalInSeconds: 10
    #   время ожидания сигнала eureka, если сигнал о работоспособности не постает, прежде чем Eureka его отключит
    leaseExpirationDurationInSeconds: 30